version: 2

sources:
  - name: raw      # ← alias du dataset gz_raw_data
    schema: gz_raw_data
    description: "Données brutes extraites pour le projet gz"

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Données de ventes brutes"
        columns:
          - name: id
            description: "Identifiant unique de la vente"
          - name: date
            description: "Date de la vente"
          # Ajoute d'autres colonnes si tu veux les documenter

      - name: product
        identifier: raw_gz_product
        description: "Liste des produits"
        columns:
          - name: id
            description: "ID produit"
          - name: price
            description: "Prix de vente"

      - name: ship
        identifier: raw_gz_ship
        description: "Données d’expédition"
        columns:
          - name: id
            description: "Identifiant de l’expédition"
          - name: shipping_fee
            description: "Frais d’expédition"
